package com.jdbcwork;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class Main {
	
	public static void main(String[] args)  {
		Employee employee = new Employee("Esraa", "alaarag");
		// TODO Auto-generated method stub
		Connection conn=null;
		Statement stmt=null;
		try {
		Class.forName("oracle.jdbc.driver.OracleDriver");
		String URL ="jdbc:oracle:thin:@localhost:1521:orcl";
		Properties info = new Properties();
		info.put("user","sys as SYSDBA");
		info.put("password", "password123");
		conn = DriverManager.getConnection(URL , info);
		stmt=conn.createStatement();
////		creating Employees table
//		String sql ="create table Employees ( "
//				+ "EmployeeNo number(10) generated by default on null as IDENTITY PRIMARY KEY, "
//				+ "firstName  VARCHAR(255), "
//				+ "lastName VARCHAR(255), "
//				+ "time_in VARCHAR(255), "
//				+ "time_out VARCHAR(255))";
//		stmt.execute(sql);
		conn.close();
		employee.createNewEmployee();
		} catch (SQLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		} catch (ClassNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		}finally {
			
		}
	}

}
